@domain = https://localhost:4000

###
# 이메일 인증 요청
POST {{domain}}/auth/send-code
Content-Type: application/json

{
  "email": "user1@gmail.com"
}

###
# 이메일 인증번호 검증
POST {{domain}}/auth/verify-code
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "code": "195183"
}