@domain = https://localhost:4000
@accessToken = {{loginToken.response.body.$.accessToken}}
@refreshToken = {{loginToken.response.body.$.refreshToken}}

###
# 로그인
# @name loginToken
POST {{domain}}/auth/login
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "123qweQWE!"
}

###
# 상품 등록 <OCI 이미지 버킷 미연결>
POST {{domain}}/business/products
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "테스트 상품",
  "description": "테스트 상품 설명",
  "price": "10000",
  "stock": "50",
  "startDay": "2024-12-01",
  "startTime": "12:00",
  "category": "전자제품",
  "status": "판매중",
  "images": [
    {
      "imageUrl": "https://example.com/main-image.jpg",
      "thumbnailUrl": "https://example.com/thumbnail-image.jpg"
    },
    {
      "imageUrl": "https://example.com/main-image-2.jpg",
      "thumbnailUrl": "https://example.com/thumbnail-image-2.jpg"
    }
  ]
}

###
# 상품 전체 조회
GET {{domain}}/business/products/my-products
Authorization: Bearer {{accessToken}}

###
# 상품 상세 조회
POST {{domain}}/business/products/details
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "productId": "1ca06d0d-e76d-4a15-8d8a-1e2e63c5f2d6"
}

# ### ---------------------------------- 에러 덩어리
# # 상품 수정 <OCI 이미지 버킷 미연결>
# PUT {{domain}}/business/products
# Authorization: Bearer {{accessToken}}
# Content-Type: application/json

# {
#   "productId": "4c7cd599-b235-4e7b-b10c-66c771135b4f",
#   "name": "수정된 상품명",
#   "description": "수정된 상품 설명",
#   "price": "20000",
#   "stock": "30",
#   "startDay": "2024-12-15",
#   "startTime": "14:00",
#   "category": "가전제품",
#   "status": "판매완료",
#   "images": [
#     {
#       "imageUrl": "https://example.com/main-image10.jpg",
#       "thumbnailUrl": "https://example.com/thumbnail-image10.jpg"
#     },
#     {
#       "imageUrl": "https://example.com/main-image-100.jpg",
#       "thumbnailUrl": "https://example.com/thumbnail-image-100.jpg"
#     }
#   ]
# }

###
# 상품 삭제 <OCI 이미지 버킷 미연결>
DELETE {{domain}}/business/products
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "productId": "1ca06d0d-e76d-4a15-8d8a-1e2e63c5f2d6"
}

###
# 모든 상품 조회 (회원/비회원 모두)
GET {{domain}}/business/products
Content-Type: application/json