@domain = https://localhost:4000
@accessToken = {{loginToken.response.body.$.accessToken}}
@refreshToken = {{loginToken.response.body.$.refreshToken}}

###
# 로그인
# @name loginToken
POST {{domain}}/auth/login
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "123qweQWE!"
}

###
# 상품 생성 <OCI 이미지 버킷 연결>
POST {{domain}}/business/products
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="image1.png"
Content-Type: image/png

< ../.oci/image1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="image2.png"
Content-Type: image/png

< ../.oci/image2.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="createProductDto"
Content-Type: application/json

{
    "name": "상품명",
    "description": "상품 설명",
    "price": "10000",
    "stock": "50",
    "startDay": "2024-12-01",
    "startTime": "12:00",
    "category": "전자제품",
    "status": "판매중",
    "images": [
        { "imageUrl": "image1.png", "isThumbnail": true },
        { "imageUrl": "image2.png", "isThumbnail": false }
    ]
}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
# 상품 전체 조회
GET {{domain}}/business/products/my-products
Authorization: Bearer {{accessToken}}

###
# 상품 상세 조회
POST {{domain}}/business/products/details
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "productId": "a9f9b86b-b872-4689-ac78-5fb22bb65adb"
}

###
# 상품 수정 <OCI 이미지 버킷 연결>
PUT {{domain}}/business/products
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="image1.png"
Content-Type: image/png

< ../.oci/image1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="image3.png"
Content-Type: image/png

< ../.oci/image3.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="updateProductDto"
Content-Type: application/json

{
  "productId": "4c7f5683-0426-4613-bf2a-54cafd18fe00",
  "name": "수정된 상품명",
  "description": "수정된 상품 설명",
  "price": "20000",
  "stock": "30",
  "startDay": "2024-12-15",
  "startTime": "14:00",
  "category": "가전제품",
  "status": "판매완료",
    "images": [
        { "imageUrl": "image1.png", "isThumbnail": true },
        { "imageUrl": "image3.png", "isThumbnail": false }
    ]
}
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
# 상품 삭제 <OCI 이미지 버킷 연결>
DELETE {{domain}}/business/products
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "productId": "4c7f5683-0426-4613-bf2a-54cafd18fe00"
}

###
# 모든 상품 조회 (회원/비회원 모두)
GET {{domain}}/business/products
Content-Type: application/json